// ============================================================================
// supabase/functions/parse-email/index.ts
//
// Receives a POST from a Pipedream workflow when a user forwards a bank
// email to the address generated by that workflow's Email trigger. Matches
// the sender to a user, extracts transaction details with regex, stores a
// pending_transactions row, and pushes an Expo notification asking the user
// to review it.
//
// Expected Pipedream workflow setup:
//   1. Trigger: "Email" (Pipedream mints a unique inbound address; users
//      forward bank emails there instead of directly to this function).
//   2. Step: "Send an HTTP request" (or a Node.js code step using `fetch`)
//      that POSTs `{{steps.trigger.event}}` as JSON to this function's URL,
//      with the shared secret appended as a query param:
//        https://<project-ref>.supabase.co/functions/v1/parse-email?token=xxx
//      Pipedream's Email trigger parses the raw email with `mailparser`, so
//      `steps.trigger.event` is a mailparser `ParsedMail` object — that's
//      the shape this handler expects below.
//
// Deploy:  supabase functions deploy parse-email --no-verify-jwt
// (--no-verify-jwt because Pipedream, not a logged-in Supabase user, calls
// this endpoint. Auth is instead enforced via WEBHOOK_TOKEN below.)
// ============================================================================

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.4";
import { parseTransactionEmail } from "./parser.ts";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
// Shared secret configured as a query param on the URL the Pipedream
// workflow POSTs to (e.g. https://<project-ref>.supabase.co/functions/v1/parse-email?token=xxx),
// so only that workflow can trigger this function. Set with:
//   supabase secrets set WEBHOOK_TOKEN=xxx
const WEBHOOK_TOKEN = Deno.env.get("WEBHOOK_TOKEN");

const EXPO_PUSH_URL = "https://exp.host/--/api/v2/push/send";

// service_role client: bypasses RLS, required to read profiles by email and
// insert into pending_transactions on the user's behalf.
const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

// ----------------------------------------------------------------------------
// Pipedream's Email trigger event (subset of fields we actually use).
// It parses the raw inbound email with the `mailparser` npm package, so
// `from`/`to` are mailparser AddressObjects: an array of {address, name}
// under `.value`, plus a pre-formatted `.text` string like "Name <email>".
// ----------------------------------------------------------------------------
interface PipedreamEmailEvent {
  from?: { value?: { address?: string; name?: string }[]; text?: string };
  subject?: string;
  text?: string; // plain-text body
  html?: string; // HTML body (fallback when text is absent)
  date?: string;
}

/** Extracts a bare email address out of a "Name <email>" style string. */
function extractEmail(from: string): string {
  const angleMatch = from.match(/<([^>]+)>/);
  return (angleMatch?.[1] ?? from).trim().toLowerCase();
}

/** Strips HTML tags down to plain text as a fallback when the plain-text body is absent. */
function htmlToText(html: string): string {
  return html
    .replace(/<style[\s\S]*?<\/style>/gi, "")
    .replace(/<script[\s\S]*?<\/script>/gi, "")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/\s+/g, " ")
    .trim();
}

async function sendExpoPushNotification(pushToken: string, body: string) {
  try {
    const res = await fetch(EXPO_PUSH_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
        "Accept-Encoding": "gzip, deflate",
      },
      body: JSON.stringify({
        to: pushToken,
        sound: "default",
        title: "New transaction detected!",
        body,
        data: { screen: "Inbox" },
      }),
    });
    if (!res.ok) {
      console.error("Expo push request failed:", res.status, await res.text());
    }
  } catch (err) {
    // A failed push notification should never fail the whole webhook —
    // the transaction is already safely stored and reviewable in-app.
    console.error("Expo push error:", err);
  }
}

Deno.serve(async (req: Request) => {
  if (req.method !== "POST") {
    return new Response("Method Not Allowed", { status: 405 });
  }

  if (WEBHOOK_TOKEN) {
    const url = new URL(req.url);
    if (url.searchParams.get("token") !== WEBHOOK_TOKEN) {
      return new Response("Unauthorized", { status: 401 });
    }
  }

  let payload: PipedreamEmailEvent;
  try {
    payload = await req.json();
  } catch {
    return new Response("Invalid JSON body", { status: 400 });
  }

  const senderEmail =
    payload.from?.value?.[0]?.address?.toLowerCase() ?? extractEmail(payload.from?.text ?? "");
  const rawText = payload.text?.trim() || htmlToText(payload.html ?? "");

  if (!senderEmail || !rawText) {
    return new Response("Missing sender or body", { status: 400 });
  }

  // 1. Identify the user by matching the forwarding address to a profile.
  const { data: profile, error: profileError } = await supabase
    .from("profiles")
    .select("id, expo_push_token")
    .ilike("email", senderEmail)
    .maybeSingle();

  if (profileError) {
    console.error("Error looking up profile:", profileError);
    return new Response("Internal error", { status: 500 });
  }

  if (!profile) {
    // No matching user — silently accept so Pipedream doesn't retry forever,
    // but do nothing further. Nothing to notify, nothing to store.
    console.warn(`No profile found for forwarding address: ${senderEmail}`);
    return new Response("OK (no matching user)", { status: 200 });
  }

  // 2. Extract amount / type / merchant from the email body via regex.
  const parsed = parseTransactionEmail(rawText);

  // 3. Store as a pending transaction awaiting user approval.
  const { error: insertError } = await supabase.from("pending_transactions").insert({
    user_id: profile.id,
    amount: parsed.amount,
    type: parsed.type,
    merchant: parsed.merchant,
    raw_text: rawText.slice(0, 5000), // guard against pathologically large bodies
    status: "pending",
  });

  if (insertError) {
    console.error("Error inserting pending transaction:", insertError);
    return new Response("Internal error", { status: 500 });
  }

  // 4. Notify the user's device, if we have a push token on file.
  if (profile.expo_push_token) {
    const amountLabel = parsed.amount ? ` ($${parsed.amount.toFixed(2)})` : "";
    await sendExpoPushNotification(
      profile.expo_push_token,
      `New transaction detected${amountLabel}! Tap to review.`,
    );
  }

  return new Response("OK", { status: 200 });
});
