// ============================================================================
// supabase/functions/parse-email/index.ts
//
// Receives a POST from a Pipedream workflow when a user forwards a bank
// email to the address generated by that workflow's Email trigger. Identifies
// the user, extracts transaction details with regex, stores a
// pending_transactions row, and pushes an Expo notification asking the user
// to review it.
//
// Identifying the user: every profile has a forwarding_token (see migration
// 0006), and the app shows each user a personalized address of the form
// base+<token>@pipedream.net. We try that token first, read out of (in
// order) the X-Forwarded-To header, then the `to` address, then fall back
// to matching From by email. Three sources because forwarding mechanisms
// disagree on what ends up where: an auto-forward *filter rule* routes at
// the SMTP level to the personalized address but typically leaves the
// message's own To: header as the original recipient — the destination
// only shows up in X-Forwarded-To (added by the relay) — while a manual
// "Forward" doesn't add that header at all, but does put the personalized
// address in `to` (since it's the actual recipient of the new message) and
// rewrites From to the forwarder's own address, which is what the final
// fallback catches.
//
// Expected Pipedream workflow setup:
//   1. Trigger: "Email" (Pipedream mints a unique inbound address; users
//      forward bank emails there instead of directly to this function).
//   2. Step: "Send an HTTP request" (or a Node.js code step using `fetch`)
//      that POSTs `{{steps.trigger.event}}` as JSON to this function's URL,
//      with the shared secret appended as a query param:
//        https://<project-ref>.supabase.co/functions/v1/parse-email?token=xxx
//      Pipedream's Email trigger parses the raw email with `mailparser`, so
//      `steps.trigger.event` is a mailparser `ParsedMail` object — that's
//      the shape this handler expects below.
//
// Deploy:  supabase functions deploy parse-email --no-verify-jwt
// (--no-verify-jwt because Pipedream, not a logged-in Supabase user, calls
// this endpoint. Auth is instead enforced via WEBHOOK_TOKEN below.)
// ============================================================================

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.4";
import { selectParser } from "./parsers/index.ts";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
// Shared secret configured as a query param on the URL the Pipedream
// workflow POSTs to (e.g. https://<project-ref>.supabase.co/functions/v1/parse-email?token=xxx),
// so only that workflow can trigger this function. Set with:
//   supabase secrets set WEBHOOK_TOKEN=xxx
const WEBHOOK_TOKEN = Deno.env.get("WEBHOOK_TOKEN");

const EXPO_PUSH_URL = "https://exp.host/--/api/v2/push/send";

// service_role client: bypasses RLS, required to read profiles by email and
// insert into pending_transactions on the user's behalf.
const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

// ----------------------------------------------------------------------------
// Pipedream's Email trigger event (subset of fields we actually use).
// mailparser normally structures `from`/`to` as AddressObjects ({value:
// [{address, name}], text}), but in practice this has also shown up as a
// bare address string — so MailAddressField accepts either and
// extractAddress() below handles both. `headers`/`headerLines` are
// mailparser's usual home for anything not promoted to a top-level field
// (like X-Forwarded-To), but that too has shown up flattened directly onto
// the event instead — getHeader() checks all three shapes.
// ----------------------------------------------------------------------------
type MailAddressField = string | { value?: { address?: string; name?: string }[]; text?: string };

interface PipedreamEmailEvent {
  from?: MailAddressField;
  to?: MailAddressField;
  subject?: string;
  text?: string; // plain-text body
  html?: string; // HTML body (fallback when text is absent)
  date?: string;
  headers?: Record<string, string | string[]>;
  headerLines?: { key?: string; line?: string }[];
  [header: string]: unknown; // arbitrary headers Pipedream may flatten onto the event, e.g. "x-forwarded-to"
}

/** Extracts a bare email address out of a "Name <email>" (optionally comma-separated) string. */
function extractEmail(raw: string): string {
  const first = raw.split(",")[0] ?? raw;
  const angleMatch = first.match(/<([^>]+)>/);
  return (angleMatch?.[1] ?? first).trim().toLowerCase();
}

/** Extracts a lowercased address out of a from/to field, whichever of the two shapes it arrived as. */
function extractAddress(field: MailAddressField | undefined): string {
  if (!field) return "";
  if (typeof field === "string") return extractEmail(field);
  return field.value?.[0]?.address?.toLowerCase() ?? extractEmail(field.text ?? "");
}

/** Case-insensitively reads a header value, trying every shape it might have arrived in. */
function getHeader(payload: PipedreamEmailEvent, name: string): string | null {
  const lower = name.toLowerCase();

  const direct = payload[lower];
  if (typeof direct === "string" && direct) return direct;

  const fromHeaders = payload.headers?.[lower];
  if (typeof fromHeaders === "string" && fromHeaders) return fromHeaders;
  if (Array.isArray(fromHeaders) && fromHeaders[0]) return fromHeaders[0];

  const line = payload.headerLines?.find((h) => h.key?.toLowerCase() === lower)?.line;
  if (line) {
    const colonIndex = line.indexOf(":");
    return (colonIndex === -1 ? line : line.slice(colonIndex + 1)).trim();
  }

  return null;
}

/** Extracts the "+tag" subaddress out of an email's local-part, e.g. "base+ab12cd@x.com" -> "ab12cd". */
function extractForwardingToken(address: string): string | null {
  const local = address.split("@")[0] ?? "";
  const plusIndex = local.indexOf("+");
  if (plusIndex === -1) return null;
  const token = local.slice(plusIndex + 1).trim();
  return token || null;
}

/** Strips HTML tags down to plain text as a fallback when the plain-text body is absent. */
function htmlToText(html: string): string {
  return html
    .replace(/<style[\s\S]*?<\/style>/gi, "")
    .replace(/<script[\s\S]*?<\/script>/gi, "")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/\s+/g, " ")
    .trim();
}

async function sendExpoPushNotification(pushToken: string, body: string) {
  try {
    const res = await fetch(EXPO_PUSH_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
        "Accept-Encoding": "gzip, deflate",
      },
      body: JSON.stringify({
        to: pushToken,
        sound: "default",
        title: "New transaction detected!",
        body,
        data: { screen: "Inbox" },
      }),
    });
    if (!res.ok) {
      console.error("Expo push request failed:", res.status, await res.text());
    }
  } catch (err) {
    // A failed push notification should never fail the whole webhook —
    // the transaction is already safely stored and reviewable in-app.
    console.error("Expo push error:", err);
  }
}

Deno.serve(async (req: Request) => {
  if (req.method !== "POST") {
    return new Response("Method Not Allowed", { status: 405 });
  }

  if (WEBHOOK_TOKEN) {
    const url = new URL(req.url);
    if (url.searchParams.get("token") !== WEBHOOK_TOKEN) {
      return new Response("Unauthorized", { status: 401 });
    }
  }

  let payload: PipedreamEmailEvent;
  try {
    payload = await req.json();
  } catch {
    return new Response("Invalid JSON body", { status: 400 });
  }

  const senderEmail = extractAddress(payload.from);
  // X-Forwarded-To first: auto-forward rules (Gmail's "Forwarding and
  // POP/IMAP" included) route to it at the SMTP level but typically leave
  // the message's own To: header as the original recipient, so `to` alone
  // would miss the personalized address entirely for that setup. Manual
  // "Forward" doesn't add this header, hence falling back to `to`. Each
  // source is tried independently for a token — a present-but-unhelpful
  // X-Forwarded-To (e.g. no "+tag" on it) still falls through to `to`,
  // rather than only falling back when the header is missing outright.
  const xForwardedTo = getHeader(payload, "x-forwarded-to");
  const toAddress = extractAddress(payload.to);
  const forwardingToken =
    (xForwardedTo ? extractForwardingToken(extractEmail(xForwardedTo)) : null) ??
    (toAddress ? extractForwardingToken(toAddress) : null);
  const htmlText = payload.html ? htmlToText(payload.html) : "";
  const rawText = payload.text?.trim() || htmlText;

  if (!rawText) {
    return new Response("Missing body", { status: 400 });
  }
  if (!forwardingToken && !senderEmail) {
    return new Response("Missing sender", { status: 400 });
  }

  // 1. Identify the user: forwarding_token first (see above for where it's
  // read from), From-header email as a fallback.
  type ProfileRow = { id: string; expo_push_token: string | null };
  let profile: ProfileRow | null = null;

  if (forwardingToken) {
    const { data, error } = await supabase
      .from("profiles")
      .select("id, expo_push_token")
      .eq("forwarding_token", forwardingToken)
      .maybeSingle();

    if (error) {
      console.error("Error looking up profile by forwarding token:", error);
      return new Response("Internal error", { status: 500 });
    }
    profile = data;
  }

  if (!profile && senderEmail) {
    const { data, error } = await supabase
      .from("profiles")
      .select("id, expo_push_token")
      .ilike("email", senderEmail)
      .maybeSingle();

    if (error) {
      console.error("Error looking up profile by sender email:", error);
      return new Response("Internal error", { status: 500 });
    }
    profile = data;
  }

  if (!profile) {
    // No matching user — silently accept so Pipedream doesn't retry forever,
    // but do nothing further. Nothing to notify, nothing to store.
    console.warn(
      `No profile found for forwarding token "${forwardingToken}" or sender "${senderEmail}"`,
    );
    return new Response("OK (no matching user)", { status: 200 });
  }

  // 2. Pick a bank-specific parser (Strategy Pattern — see parsers/index.ts),
  // falling back to the generic regex engine when no bank is recognized.
  // Subject and both body variants are folded into one search string since
  // BankParser.parse() takes a single `text` argument by design (see
  // parsers/types.ts) — keeps every parser's signature uniform regardless of
  // how many source fields it wants to consider.
  const subject = payload.subject ?? "";
  const searchText = [subject, rawText, htmlText && htmlText !== rawText ? htmlText : ""]
    .filter(Boolean)
    .join("\n");
  const parser = selectParser(searchText, subject);
  const parsed = parser.parse(searchText);

  // 3. Store as a pending transaction awaiting user approval.
  const { error: insertError } = await supabase.from("pending_transactions").insert({
    user_id: profile.id,
    amount: parsed.amount,
    type: parsed.type,
    merchant: parsed.merchant,
    bank_name: parser.bankName,
    date: parsed.date,
    raw_text: rawText.slice(0, 5000), // guard against pathologically large bodies
    status: "pending",
  });

  if (insertError) {
    console.error("Error inserting pending transaction:", insertError);
    return new Response("Internal error", { status: 500 });
  }

  // 4. Notify the user's device, if we have a push token on file.
  if (profile.expo_push_token) {
    const amountLabel = parsed.amount ? ` ($${parsed.amount.toFixed(2)})` : "";
    await sendExpoPushNotification(
      profile.expo_push_token,
      `New transaction detected${amountLabel}! Tap to review.`,
    );
  }

  return new Response("OK", { status: 200 });
});
